name: CI
on:
  push:
    # branches:
    #   - master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: "3.8"
          environment-file: .github/environment-docs.yaml
          activate-environment: scikit-mine-docs
          auto-activate-base: false

      - name: Install scikit-mine
        shell: bash -l {0}
        run: python -m pip install -e .

      - name: Build docs
        shell: bash -l {0}
        run: make docs

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.SKMINE_GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_build/html
          CLEAN: true
