name: Check MDL compression is lossless
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.x
      - name: Install external dependencies
        run: pip install -U numpy
      - name: Install project
        run: python setup.py install
      - name: SLIM RECONSTRUCTION
        run: python .github/mdl_reconstruct/slim.py
      - name: PERIODIC RECONSTRUCTION
        run: python .github/mdl_reconstruct/periodic.py
