name: Check MDL compression is lossless
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install external dependencies
        run: pip install -U numpy
      - name: MDL reconstruction
        run: python setup.py install && cd .github/ && python mdl_reconstruct.py
