name: sklearn_compat
on:
  - pull_request:
    paths:
    - skmine/
    - .github/check_sklearn_compat.py
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install external dependencies
        run: pip install scikit-learn
      - name: check compatibility
        run: python setup.py install && cd .github/ && python check_sklearn_compat.py
