name: SLIM_metrics
pull_request:
  paths:
  - 'skmine/itemsets/*.py'
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.SKMINE_GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro slim_metrics
          git fetch --prune
          dvc metrics diff --show-md master > report.md
          cml-send-comment report.md
